### ISSUE TITLE
[Feature Request] Define cells manually

### ISSUE THREAD

**Issue by JulioHC00** [dccsillag/magma-nvim#39] opened 2022-01-09 09:44 UTC
**Is your feature request related to a problem? Please describe.**
Not precisely a problem but it would be great to have the option of defining cells manually (e.g using `# %%`) so that everything is in the same file and there's no need to save and load another file whenever editing code.

**Describe the solution you'd like**
Add an option that either lets you use a predefined "marker" to define a new cell or lets you define your own marker.

**Describe alternatives you've considered**
Using visual selection and running the code to create a cell. However, if I forget to save or load the json file it will start throwing errors and I lose all the cells. I would prefer if I can define the cells myself using `# %%`.

**Comment by dccsillag** [comment] 2022-01-23 23:37
Duplicate of https://github.com/dccsillag/magma-nvim/issues/19.

**Closed by dccsillag** 2022-01-23 23:37 UTC
Labels: enhancement
